### ISSUE TITLE
Build Search Tree for POI

### ISSUE THREAD

**Issue by wipegup** [copilotroadtrip/CoPilotBackend#13]
Build a balanced BST as a way to aid search for POI along route

Could make `cKDTree` with `scipy`

Note, Possible road files at: https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-geodatabase-file.html

**Comment by milevy1** [comment]
Python microservice?

**Comment by wipegup** [comment]
Probably,

I think it will significantly speed search times

**Comment by wipegup** [comment]
This looks like it would be slower than a DB call; closing
