### ISSUE TITLE
Speed testing DB vs Binary search tree

### ISSUE THREAD

**Issue by milevy1** [copilotroadtrip/CoPilotBackend#18]
Comparing the performance of two different strategies for determining:
- Given a coordinate (longitude/latitude)
- What `points of interest(s) [POI]` (if any) overlap that coordinate?

1. SQL
- Seed database with all POI contraining their name, ne_lat, ne_long, sw_lat, sw_long
`pseudocode`
coordinate.latitude = x
coordinate.longitude = y

```sql
SELECT *
FROM Pois p
WHERE
pois.ne_lat > 
```

**Comment by wipegup** [comment]
Completed; DB query seems to be faster than search tree
