### ISSUE TITLE
Create POI seed file for JUST western states

### ISSUE THREAD

**Issue by wipegup** [copilotroadtrip/CoPilotBackend#34]
Must be fewer than 10k records for free tier

OR 

Upgrade Heroku DB

**Comment by milevy1** [comment]
Upgraded to `Hobby Basic` plan for Heroku Postgres.  Allows 10,000,000 rows for $9/month.

I will add a new issue to make a new seed file for less POIs, such as just the Western United States.  We can downgrade to this after demo maybe
