### ISSUE TITLE
Add intermediate POIs to `POST /api/v1/trips`

### ISSUE THREAD

**Issue by wipegup** [copilotroadtrip/CoPilotBackend#36]
Add information for intermediate POIS / leg info in return for POST /api/v1/trips

This will make things slow

**Comment by milevy1** [comment]
What do you think about dividing the request into two?  

- POST /api/v1/trips could just return the origin and destination data
- Make this request also insert a "trip.token" to the trips table
- Queue Redis to go start finding the POIs and insert them into the `trip_pois` table
- Response would include the "trip.token" to use for future requests, front-end could store in cookie

- GET /api/v1/pois?trip_token=12345
- Response would be all pois along that trip

**Comment by wipegup** [comment]
We definitely need to make some architecture decisions in the next couple days.

For now I'm orienting toward putting everything in the response of the `POST`, and splitting out from there

**Comment by wipegup** [comment]
This is addressed in more recent issues
