### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by wipegup** [copilotroadtrip/CoPilotBackend#4]
Configure Travis CI to do:

- [x] Run test suite upon PR creation
- [x] Auto-deploy to "Review" Heroku environment upon PR creation
- [x] Auto-deploy to "Production" Heroku environment upon PR merge

https://devcenter.heroku.com/articles/pipelines#deployment-with-pipelines

**Comment by milevy1** [comment]
Heroku is now setup to auto-deploy to "Production" on Heroku upon PR merge and succssful CI

https://devcenter.heroku.com/articles/github-integration#automatic-deploys

**Comment by milevy1** [comment]
# Heroku Review app configuration

- Heroku will now deploy a "Review" app upon PR creation.
- Settings for this pipeline configuration are stored in the root `app.json` file here: https://github.com/copilotroadtrip/CoPilotBackend/blob/master/app.json

References: 
https://devcenter.heroku.com/articles/pipelines
https://devcenter.heroku.com/articles/github-integration-review-apps
